### ISSUE TITLE
cpanm  Markdown::Pod fails

### ISSUE THREAD

**Issue by melezhik** [keedi/Markdown-Pod#11]
Hi! I could not install Markdown::Pod  

Regards

Alexey

https://gist.github.com/melezhik/b22b97c3b912ee6bf14fe816e6273f25

```
$ perl -v

This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi
(with 33 registered patches, see perl -V for more detail)

Copyright 1987-2012, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.
```

**Comment by keedi** [comment]
Thanks for the error report. I'll check it in a few days!

**Comment by melezhik** [comment]
HI @keedi , any news here?

**Comment by Grinnz** [comment]
From test reports, this appears to be failing on any Perl older than 5.20; there appears to be an incompatibility with the type constraint on the Markdown::Pod::Handler _output attribute.

**Comment by melezhik** [comment]
Yeah. I think I am going to close this one, as I would rather upgrade my Perl. Thanks @Grinnz

**Comment by karenetheridge** [comment]
There should be a fairly straightforward workaround for this.
