### ISSUE TITLE
Fails during tests.  Force installs it, but it doesn't work (same kinds of errors as below)

### ISSUE THREAD

**Issue by markwilkinson** [keedi/Markdown-Pod#8]
# Versions for all modules listed in MYMETA.json (including optional ones):
# 
# === Configure Requires ===
# 
#     Module              Want    Have
#     ------------------- ---- -------
#     ExtUtils::MakeMaker 6.17 7.10_02
# 
# === Build Requires ===
# 
#     Module              Want    Have
#     ------------------- ---- -------
#     ExtUtils::MakeMaker  any 7.10_02
# 
# === Test Requires ===
# 
#     Module              Want     Have
#     ------------------- ---- --------
#     Exporter            5.57     5.72
#     ExtUtils::MakeMaker  any  7.10_02
#     File::Spec           any  3.63_01
#     Test::More           any 1.302106
# 
# === Test Recommends ===
# 
#     Module         Want     Have
#     ---------- -------- --------
#     CPAN::Meta 2.120900 2.150005
# 
# === Runtime Requires ===
# 
#     Module                         Want   Have
#     ------------------------------ ---- ------
#     Getopt::Long                    any   2.48
#     List::Util                      any   1.49
#     Markdent                       0.25   0.27
#     Moose                           any 2.2007
#     MooseX::Params::Validate        any   0.21
#     MooseX::SemiAffordanceAccessor  any   0.10
#     MooseX::StrictConstructor       any   0.21
#     Text::Table::Tiny               any   0.04
#     constant                        any   1.33
#     namespace::autoclean            any   0.28
# 
t/00-report-prereqs.t ................. ok   
t/001-line-break.t .................... Bareword "Str" not allowed while "strict subs" in use at /home/osboxes/.cpan/build/Markdown-Pod-0.006-mOmt2h/blib/lib/Markdown/Pod/Handler.pm line 70.
BEGIN not safe after errors--compilation aborted at /home/osboxes/.cpan/build/Markdown-Pod-0.006-mOmt2h/blib/lib/Markdown/Pod/Handler.pm line 457.
Compilation failed in require at /home/osboxes/.cpan/build/Markdown-Pod-0.006-mOmt2h/blib/lib/Markdown/Pod.pm line 13.
BEGIN failed--compilation aborted at /home/osboxes/.cpan/build/Markdown-Pod-0.006-mOmt2h/blib/lib/Markdown/Pod.pm line 13.
Compilation failed in require at t/lib/Markdown/Pod/Test.pm line 8.
BEGIN failed--compilation aborted at t/lib/Markdown/Pod/Test.pm line 8.
Compilation failed in require at t/001-line-break.t line 5.
BEGIN failed--compilation aborted at t/001-line-break.t line 5.
# Looks like your test exited with 255 before it could output anything.
t/001-line-break.t .................... Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 1/1 subtests 
t/2011-12-01.mkd.t .................... Bareword "Str" not allowed while "strict subs" in use at /home/osboxes/.cpan/build/Markdown-Pod-0.006-mOmt2h/blib/lib/Markdown/Pod/Handler.pm line 70.

**Comment by markwilkinson** [comment]
From the documentation (http://search.cpan.org/~ether/Moose-2.2007/lib/Moose.pm)

isa => $type_name

The isa option uses Moose's type constraint facilities to set up runtime type checking for this attribute. Moose will perform the checks during class construction, and within any accessors. **The $type_name argument must be a string.** The string may be either a class name or a type defined using Moose's type definition features. (Refer to Moose::Util::TypeConstraints for information on how to define a new type, and how to retrieve type meta-data).


So... it is unclear how your code or test suite ever worked...?   (I know it does, because it works for me on some other machines - not all)   But regardless...

**Comment by rsrpsinr** [comment]
strange.. this worked before for me but recently, new installation of this module has been throwing this test error.

**Comment by zmughal** [comment]
I have put together a fix for this at <https://github.com/keedi/Markdown-Pod/pull/9>.

In the meantime, you can downgrade to Markdent v0.26 and install Markdown::Pod again:

```shell
cpanm Markdent@0.26 Markdown::Pod@0.006
```

**Comment by keedi** [comment]
Thx!! @zmughal++

I'm sorry that the response is **too** late. I'm preparing to release.

**Comment by keedi** [comment]
I've just released [0.007](https://metacpan.org/release/KEEDI/Markdown-Pod-0.007).

Thanks again. :)

**Comment by zmughal** [comment]
Thank you! I just installed the new version and all is well! :-)
